name: docs

on: push

jobs:
  build:
    name: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: git clone https://github.com/shuding/nextra-docs-template
      - run: cd ./nextra-docs-template && npm i && cd ../
      - run: npm run --prefix ./nextra-docs-template build



