name: build-docs
jobs:
  build-docs:
    name: build-docs
    runs-on: ubuntu-latest
    on: push
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun i next@^13.0.6 nextra@2.13.4 nextra-theme-docs@2.13.4 react@^18.2.0 react-dom@^18.2.0  
      - run: bunx create-next-app docs_site --v 13.0.6 --ts --no-tailwind --no-eslint --no-app --no-src-dir --no-import-alias --empty --use-bun