name: docs

on: push

jobs:
  build:
    name: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          owner: 'shuding'
          repository: 'nextra-docs-template'
          access-token: ${{ secrets.ACCESS_TOKEN }}



